name: .NET Framework Desktop

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore NPS.sln
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
    - name: Build with MSBuild
      run: msbuild NPS.sln /p:Configuration=Release

    # Upload the artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NPS_Browser.exe
        path: NPS\bin\Release
